### ISSUE TITLE
Levantar infra necessária pra começar

### ISSUE THREAD

**Issue by gomex** [mentoriaiac/iac#2]
Levando em consideração que começaremos com consul e logo em seguida Loki.

Precisamos definir quantas máquinas usaremos para começar com ambos.

Levando em conta que tudo precisa já nascer em produção com alta disponibilidade, inclusive entre dois datacenters distintos.

Podemos pensar no CF como LB ou o próprio provedor do datacenter.

O Consul será direto em VMs e o Loki seria no Kubernetes, ou seja, levando em conta que o k8s o ideal é no mínimo 3 managers e 3 workers. Já partimos dessa perspectiva.

**Comment by afonsoaugusto** [comment]
Registrando reunião 28/04/2021.

A ideia da reunião é termos uma ideia do desenho básico para a infraestrutura para prover um serviço multi-tenant para observabilidade. Semelhante à um NewRelic ou Datadog.

@gomex, a ideia de ter um consul logo de inicio seria para conhecermos os servidores que iremos consumir as métricas?
Neste caso trabalharíamos com um modelo Ativo, onde nós iriamos até o servidor para coletar as informações.

![GCP-Observabilidade-Page-1 (1)](https://user-images.githubusercontent.com/2923610/116484732-17874580-a860-11eb-832b-2ccbcf8ed3c2.png)

Acho que para um produto de observabilidade, poderíamos trabalhar com um modelo passivo onde teríamos um agente e este publicaria as métricas em um endpoint nosso.

![GCP-Observabilidade (2)](https://user-images.githubusercontent.com/2923610/116482734-20761800-a85c-11eb-8c43-0eee6c4b4bec.png)

Onde podemos ter a organização de mais de 1 zona para alta disponibilidade, e no futuro podemos pensar em uma solução de DR com mais de uma região ou outra cloud.

![GCP-Observabilidade-Page-2](https://user-images.githubusercontent.com/2923610/116484472-81ebb600-a85f-11eb-9ca0-47a54f4ee543.png)
 
Podemos ter um consul para registro e comunicação dos servidores internos, porém acho que ele não é necessário para o cliente publicar as suas métricas. 

Ai, o consul servindo a nossa aplicação, ele pode ficar dentro da rede privada seguindo a [arquitetura de referencia](https://learn.hashicorp.com/tutorials/consul/reference-architecture#single-consul-datacenter-with-a-kubernetes-cluster)
<img width="600" alt="k8s-cluster-consul-datacenter" src="https://user-images.githubusercontent.com/2923610/116485141-e0656400-a860-11eb-89d9-2095602c7e0c.png">

Presentes:
@lariskovski
@klebercabral
@pablosmith
@afonsoaugusto
